### PR TITLE
updated SV info

### PR DESCRIPTION
**Pull request by alexiiion**
- updated dates for SVs arriving & leaving
- added Pascal to SV section

### CODE REVIEW

**Comment by batuhancerli** [comment]
hi, I could not run npm install which is the requirenment for start the methamaterial editor

**Comment by LeaVerou** [comment]
@batuhancerli Hi, could you please provide some more detail? What is a methamaterial editor? What error did you get when you were trying to run `npm install`? 
Also, it would be best to start a new issue in https://github.com/LeaVerou/uist2017/issues instead of commenting in an unrelated pull request.

**Comment by alexiiion** [comment]
@batuhancerli you are in a completely different repository :) can you please ask in the correct repository: https://github.com/jfrohnhofen/metamaterial-mechanisms

@LeaVerou this has nothing to do with this repo :) sorry.

**Comment by batuhancerli** [comment]
I could not ask any question via this link. Could you give me a hand by the email? My problem is that after downloading the node.js , I could not run the npm install because I do not understand its function.


alexiiion <notifications@github.com> şunları yazdı (11 Nis 2017 14:38):

**Comment by LeaVerou** [comment]
You can ask a question via this link: https://github.com/jfrohnhofen/metamaterial-mechanisms/issues/new

**Comment by LeaVerou** [comment]
`npm install` is a terminal command. You would first need to navigate to the project directory via the terminal (`cd path/to/directory/here`). Maybe look for a tutorial online for using the terminal?

**Comment by batuhancerli** [comment]
While npm intall was operating, I encounterd this error and I was stuck.
This is my issue, please help me

2017-04-11 21:16 GMT+03:00 Lea Verou <notifications@github.com>:

**Comment by LeaVerou** [comment]
Please post in the link I gave you above. This is a completely unrelated repository.

**Pull request merged**
